[workspace]
resolver = "3"
members = [
  "crates/chewing_tip_core",
  "crates/tsfreg",
  "tip",
  "vendor/libchewing",
  "xtask"
]

[workspace.package]
version = "0.2.0"

[workspace.dependencies]
anyhow = "1"
chewing = "0.14.0-alpha.2"
embed-resource = "3.0.1"
log = "0.4.29"
scoped-error = "0.1.0"
serde = { version = "1.0.228", features = ["derive"] }

[profile.release]
debug = true
lto = "thin"
panic = "abort"

[patch."crates-io"]
# Pinyin needs matching libchewing's API can't express (see docs DESIGN.md).
chewing = { path = "vendor/libchewing" }
# chewing = { git = "https://codeberg.org/chewing/libchewing.git" }
# chewing = { path = "../libchewing/" }
