// SPDX-License-Identifier: GPL-3.0-or-later

use scoped_error::{Error, expect_error};

mod dist;
mod download;
mod version;
mod zip;

mod flags {
    use super::dist::Target;

    xflags::xflags! {
        src "src/main.rs"

        /// cargo-xtask helper
        cmd xtask {
            /// Update the version.rc file.
            cmd update-version {
                /// The major version of the release. (u32)
                required --major MAJOR: u32
                /// The minor version of the release. (u32)
                required --minor MINOR: u32
                /// The patch version of the release. (u32)
                required --patch PATCH: u32
                /// Optional build number (u32)
                optional -b, --build BUILD_NUMBER: u32
            }
            /// Build the portable package in dist/.
            cmd dist {
                /// Target platform [gnu, gnullvm, msvc]
                optional -t, --target TARGET: Target
                /// Build release artifact
                optional --release
                /// Build nightly artifact
                optional --nightly
                /// Build for ARM64 Windows instead of x64 (x64 apps there can't use it)
                optional --arm64
                /// Also build an x64 MSI installer with wixl (msitools)
                optional --msi
            }
        }
    }
    // generated start
    // The following code is generated by `xflags` macro.
    // Run `env UPDATE_XFLAGS=1 cargo build` to regenerate.
    #[derive(Debug)]
    pub struct Xtask {
        pub subcommand: XtaskCmd,
    }

    #[derive(Debug)]
    pub enum XtaskCmd {
        UpdateVersion(UpdateVersion),
        Dist(Dist),
    }

    #[derive(Debug)]
    pub struct UpdateVersion {
        pub major: u32,
        pub minor: u32,
        pub patch: u32,
        pub build: Option<u32>,
    }

    #[derive(Debug)]
    pub struct Dist {
        pub target: Option<Target>,
        pub release: bool,
        pub nightly: bool,
        pub arm64: bool,
        pub msi: bool,
    }

    impl Xtask {
        #[allow(dead_code)]
        pub fn from_env_or_exit() -> Self {
            Self::from_env_or_exit_()
        }

        #[allow(dead_code)]
        pub fn from_env() -> xflags::Result<Self> {
            Self::from_env_()
        }

        #[allow(dead_code)]
        pub fn from_vec(args: Vec<std::ffi::OsString>) -> xflags::Result<Self> {
            Self::from_vec_(args)
        }
    }
    // generated end
}

fn main() -> Result<(), Error> {
    expect_error("failed to run command", || {
        let flags = flags::Xtask::from_env()?;

        match flags.subcommand {
            flags::XtaskCmd::UpdateVersion(flags) => {
                version::update_version(flags)?;
            }
            flags::XtaskCmd::Dist(flags) => {
                dist::dist(flags)?;
            }
        }

        Ok(())
    })
}
